properties/urls.py
# my_real_estate_site/properties/urls.py
from django.urls import path
from . import views

app_name = 'properties' # Namespace for URLs

urlpatterns = [
    path('', views.home_view, name='home'),
    path('properties/', views.property_list_view, name='property_list'),
    path('properties/<slug:slug>/', views.property_detail_view, name='property_detail'),
    path('services/', views.service_list_view, name='service_list'),
    path('projects/', views.project_list_view, name='project_list'),
    path('projects/<slug:slug>/', views.project_detail_view, name='project_detail'),
    path('contact/', views.contact_view, name='contact'),
    path('about/', views.about_view, name='about'),
]

urls.py
# my_real_estate_site/my_real_estate_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('properties.urls')), # Include your app's URLs
]

# Serve static and media files during development ONLY
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
{# my_real_estate_site/my_real_estate_site/templates/partials/footer.html #}
<footer>
    <div class="container">
        <p>&copy; 2025 FAKEMA. All rights reserved.</p>
        <p>Douala, CAMEROUN | +237 6XX XXX XXX | info@fakemabuilding.com</p>
    </div>
</footer>

templates/partials/navbar.html
{# my_real_estate_site/my_real_estate_site/templates/partials/navbar.html #}
<nav>
    <div class="container" style="display: flex; justify-content: space-between; align-items: center;">
        <a href="{% url 'properties:home' %}" class="logo-container">
            {% load static %}
            <!-- Essayez avec .png si .jpg ne marche pas -->
            <img src="{% static 'img/logo.jpg' %}" alt="" class="logo-img" style="height: 50px; width: auto;">
         </a>
        <ul style="display: flex;">
            <li><a href="{% url 'properties:home' %}">Home</a></li>
            <li><a href="{% url 'properties:about' %}">About Us</a></li>
            <li><a href="{% url 'properties:service_list' %}">Services</a></li>
            <li><a href="{% url 'properties:property_list' %}">Properties</a></li>
            <li><a href="{% url 'properties:project_list' %}">Projects</a></li>
            <li><a href="{% url 'properties:contact' %}">Contact</a></li>
        </ul>
    </div>
</nav>